### ISSUE TITLE
Timeout per quickrun command

### ISSUE THREAD

**Issue by palikar** [emacsorphanage/quickrun#109]
Is there a plan to add a feature where one can specify how long is the timeout for a process but on a command basis? For example, `quickrun-add-command` can take an extra argument `:timeout` which controls the behavior of the specific command. 

If the effort is not that big, I could implemented it myself. Would you be interested in PR?

**Comment by jcs090218** [comment]
Sounds like a good plan! It you be great if you willing to make a PR! Thanks!

**Comment by jcs090218** [comment]
Close this too! :)
