### ISSUE TITLE
Running quickrun on a Common Lisp file doesn't work

### ISSUE THREAD

**Issue by chrisalcantara** [emacsorphanage/quickrun#112]
When I run `quickrun` in a Common Lisp file -- `test.lisp` -- I get the following error: `not found [lisp] language information`. 

Any advice? I have `clisp` installed.

**Comment by syohex** [comment]
Can you see `clisp` from emacs ? What value does `(executable-find "clisp")`  return ? If it returns `nil`, you need PATH setting.

**Comment by chrisalcantara** [comment]
Thanks for the response. 

When I run `(executable-find "clisp")` I get `"/usr/local/bin/clisp"`. So Emacs does see something.

I forgot to mention that I'm running this on macOS, with Catalina, so I'm sure that's part of the problem.

**Comment by syohex** [comment]
You need to configure `PATH` setting before loading `quickrun.el`. Could you evaluate `(quickrun--init-command-key-table)` and try again ? If it works, I suppose this is PATH configuration timing issue.

**Comment by chrisalcantara** [comment]
`(quickrun--init-command-key-table)` returns `nil` when I run `Eval`

**Comment by syohex** [comment]
Yes, `(quickrun--init-command-key-table)` returns nil, it is a setup function for compiler of each language. Could you try `M-x quickrun` in common lisp file after `M-: (quickrun--init-command-key-table)` ? Is there still problem ?

**Comment by chrisalcantara** [comment]
Nope! There doesn't seem to be any problem.

I made a small file:

```(defun say-hello (name)
  (format t " Hello, ~a! ~%" name))

(say-hello "Chris")
```

And it ran with quickrun.

**Comment by syohex** [comment]
OK. I assume you set PATH after loading `quickrun.el`. Please check it. BTW you need not to load quickrun.el, if you install quickrun.el via package manager like package.el, use-package etc. Because quickrun command is auto-loaded.

**Comment by chrisalcantara** [comment]
Checked my PATH and things seem to running correctly now. Thanks for your help. I'll close the issue.
