### ISSUE TITLE
Cannot handle spaces in path name

### ISSUE THREAD

**Issue by anihm136** [emacsorphanage/quickrun#118]
Hi, I'm using quickrun in doom emacs. I recently noticed that using quickrun in a file which has a space in its pathname causes an error, taking the part after the space as a second argument. I wonder if it is something that's easy to fix?

**Comment by jcs090218** [comment]
Sorry for the late reply!

I think this suppose to be an easy fix yet this package has no plan to further develop! You can either make a PR or elaborate more on your side's condition (like what error, how to reproduce, etc). Hope this helps! Thanks! 😄

**Comment by anihm136** [comment]
Ah okay. I'm not great at elisp, but I'll take a look and send in a PR if it's an easy fix. Thanks for the great package!

**Comment by anihm136** [comment]
I've opened a PR for this. As I said, I'm not great at elisp, so please let me know if there's anything wrong and I'll make the necessary changes

**Comment by jcs090218** [comment]
I made a few review in the PR, let me know if you have any issue with my review! Thanks! :)
