### ISSUE TITLE
quickrun-shell  binds "q" to (quickrun--eshell-window-restore) in every eshell buffer

### ISSUE THREAD

**Issue by Passky** [emacsorphanage/quickrun#121]
`quickrun-shell` creates a buffer named  *eshell-quickrun*,then quickrun--mode-map is enabled in every eshell buffer include *eshell*.
so,"q" is bind to (quickrun--eshell-window-restore) in every eshell buffer(including *eshell* buffer) instead of just in *eshell-quickrun*;;

I guess this could be a bug,and can be reproducted with minimal setup;
``` emacs-lisp
(require 'quickrun)
```

**Comment by jcs090218** [comment]
@Passky Can you check if #122 resolved your issue? Thanks! 😄

**Comment by Passky** [comment]
That works perfectly.
Thanks!
😃
