### ISSUE TITLE
Getting "ModuleNotFoundError" errors when "#!/usr/bin/env python" is used in Python scripts

### ISSUE THREAD

**Issue by falstaff1288** [emacsorphanage/quickrun#123]
Distribution: ArchLinux
Emacs: GNU Emacs 27.1
Quickrun version: 2.3.0
Python version: 3.8.5
Emacs function used: `M-x quickrun`
===

Hello,
As mentioned in the title, Python scripts are not working unless if I use a more direct path to the Python interpreter (`!#/usr/bin/python`). Example: the only error outputted in the quickrun buffer looks like this:
 
```
Traceback (most recent call last):
  File "meteo.py", line 3, in <module>
    from env_canada import ECData
ModuleNotFoundError: No module named 'env_canada'
```

I have no clue what might cause this problem, hence why I've opened this issue. Let me know if you need more details.

**Comment by syohex** [comment]
Can you get your expected python path by evaluating following s-expression in Emacs where this problem occurs ?

```lisp
(executable-find "python")
```

If you not, you need to configure path variables of Emacs. I suppose it is easy to configure same as shell by using [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell)

**Comment by falstaff1288** [comment]
This is what I get (ran in org-mode):
```
#+begin_src emacs-lisp
(executable-find "python")
#+end_src

#+RESULTS:
: /usr/bin/python
```

**Comment by falstaff1288** [comment]
Nevermind, I move my script to another folder and it's now importing the modules correctly.

Therefore, the issue is not related to quickrun.

Thanks.
