### ISSUE TITLE
output show strange like ?????

### ISSUE THREAD

**Issue by zcjava** [emacsorphanage/quickrun#127]
![image](https://user-images.githubusercontent.com/1551382/101872705-a8ff5f00-3bc0-11eb-8cbd-20287b52dfb2.png)

**Comment by syohex** [comment]
Could you show us your input file ?

**Comment by zcjava** [comment]
i run java main class by  quickrun . it output like above image;
code like :
public static void main(String[] args) {
        System.out.print("sss");
    }

**Comment by zcjava** [comment]
> Could you show us your input file ?

i run java main class by quickrun . it output like above image;
code like :
public static void main(String[] args) {
System.out.print("Test");
}

**Comment by zcjava** [comment]
i find the problem , is eshell garbage character
