### ISSUE TITLE
How to make *quickrun* stay in the same window?

### ISSUE THREAD

**Issue by michaeldickens** [emacsorphanage/quickrun#129]
If I run `(quickrun)`, it opens the `*quickrun*` buffer in a window. Then, if I run `(quickrun)` again, it moves the buffer out of the original window and into a new window. I want the `*quickrun*` buffer to stay in one window consistently so I can have my source code files in certain designated windows and `*quickrun*` in another designated window. (Note that Emacs compile commands open the `*Compilation*` buffer, and they have the behavior I want, where they will keep the buffer in the same window if it's already visible.) How do I make quickrun behave like this?

I tried using Emacs's dedicated-window functionality, but that doesn't work. If I mark the window with `*quickrun*` as a designated window and then run `(quickrun)` again, it _closes_ the window with `*quickrun*` in it and then puts `*quickrun*` in a different window.

Help on this issue is much appreciated.

**Comment by danielpza** [comment]
If I understand correctly this is what you want https://github.com/emacsorphanage/quickrun#quickrun-focus-pdefault-t?

**Comment by michaeldickens** [comment]
(Sorry for slow reply) I don't think that's what I want. `quickrun-focus-p` determines whether the focus moves to the quickrun window. My issue isn't about the focus. It's that when the *quickrun* buffer is already open and I run quickrun again, it moves *quickrun* to a different buffer, and I want it to stay in the same one. Just to make sure, I've tried with `quickrun-focus-p` both on and off, and I get the undesired behavior either way.

**Comment by michaeldickens** [comment]
Although now that I'm looking at it again, `quickrun` seems to be behaving the way I want it to. I guess the behavior got changed in a recent update. It's not 100% consistent, e.g., if I open a new window, it will change where the `*quickrun*` buffer opens. But at least `*quickrun*` appears to open in a consistent spot as long as I don't change anything with the windows.

**Comment by salehmu** [comment]
I've the same problem, it's very annoying and destroys my window arrangement
