### ISSUE TITLE
Enable GitHub Actions for this repo

### ISSUE THREAD

**Issue by jcs090218** [emacsorphanage/quickrun#141]
@tarsius Can we enable the GitHub Actions for this repo? Thanks!

**Comment by tarsius** [comment]
Let me know if you need any actions other than those defined in this organization, by Github or from verified creators on the marketplace.

**Comment by jcs090218** [comment]
![Image 1](https://user-images.githubusercontent.com/8685505/194593365-0d8c30f3-bf6b-4ba4-a6a8-6c9721a2fb6b.png)

I am using these actions,

* https://github.com/jcs090218/setup-emacs
* https://github.com/emacs-eask/setup-eask

Thanks!

**Comment by tarsius** [comment]
I've allowed these and hopefully all the dependencies:

```
emacs-eask/setup-eask@*,
jcs090218/setup-emacs-windows@*,
jcs090218/setup-emacs@*,
purcell/setup-emacs@*,
```

**Comment by tarsius** [comment]
Seems to work :smiley:

**Comment by jcs090218** [comment]
Thanks for the help! :D
